name: Automatically create pull request from development to epic branches

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  create_and_merge_pull_requests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List branches
      run: |
        git fetch --prune origin '+refs/heads/*:refs/remotes/origin/*'
        BRANCHES=$(git for-each-ref --format '%(refname:short)' 'refs/remotes/origin/epic/rc-*')
        for branchWithOrigin in $BRANCHES; do
          branch=${branchWithOrigin#origin/}
          gh pr create --base $branch --head development --title "Automated PR from development to $branch" --body "This PR was automatically opened using GitHub actions" || true
          PR_NUMBER=$(gh pr list --state open --base $branch --head development --json number --limit 1 --jq '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            echo "Pull request $PR_NUMBER exists. Proceeding to merge..."
            gh pr merge $PR_NUMBER --merge --admin
          else
            echo "Pull request does not exist for branch $branch."
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
